name: Datree CLI
description: Use the Datree CLI in a github action
author: hadarco
inputs:
  file:
    description: the file/s to be tested
    required: true
  options:
    description: the Datree CLI options to be used
    required: false
  isHelmChart:
    description: is the desired file a Helm chart?
    required: true
    default: false
  helmArguments:
    description: the Helm arguments to be used
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: 'terminal'
  color: 'black'
