apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/target-type":"ip","kubernetes.io/ingress.class":"alb"},"labels":{"app":"hn-ingress"},"name":"hn-ingress","namespace":"hn-app"},"spec":{"rules":[{"host":"hn.datree.io"},{"http":{"paths":[{"backend":{"serviceName":"service-hn","servicePort":80},"path":"/","pathType":"Prefix"}]}}]}}
    kubernetes.io/ingress.class: alb
  creationTimestamp: "2022-04-22T15:29:13Z"
  generation: 1
  labels:
    app: hn-ingress
  name: hn-ingress
  namespace: hn-app
  resourceVersion: "53000"
  uid: 34ae6aec-5c73-4334-8077-c62b7982f51d
spec:
  rules:
  - host: hn.datree.io
  - http:
      paths:
      - backend:
          service:
            name: service-hn
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
