version: 2.1
orbs:
  datree: datree/datree@1.1.8

workflows:
  policy-check:
    jobs:
      - datree/policy-check:
          path: 'testchart'
          isHelmChart: true
          cliArguments: '--schema-version 1.23.0'
