apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  labels:
    app: {{ .Values.app.name }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: {{ .Values.app.name }}
    nodePort: {{ .Values.app.nodePort }}
    port: {{ .Values.app.port }}
    protocol: {{ .Values.app.protocol }}
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}
  sessionAffinity: None
  type: LoadBalancer
