name: Generate Guide with ChatGPT API

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the Guide'
        required: true
      description:
        description: 'Description of the Guide'
        required: true

jobs:
  generate-guide:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Guide Content using ChatGPT API
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Set the prompt using the inputs
        PROMPT="Create a markdown guide for Port (docs.getport.io) titled '${{ github.event.inputs.title }}'. Description: ${{ github.event.inputs.description }}"

        # Call the OpenAI API to generate content
        RESPONSE=$(curl -sS -X POST https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d '{
                "model": "gpt-3.5-turbo",
                "messages": [{"role": "user", "content": "'"$PROMPT"'"}],
                "temperature": 0.7
              }')

        # Extract the generated guide content from the API response
        GUIDE_CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

        # Save the guide content to a markdown file
        echo "$GUIDE_CONTENT" > guide.md

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create and Push Branch with Guide
      run: |
        git checkout -b generate-guide-branch
        git add guide.md
        git commit -m "Add generated guide: ${{ github.event.inputs.title }}"
        git push origin generate-guide-branch

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: generate-guide-branch
        title: "Add Generated Guide: ${{ github.event.inputs.title }}"
        body: "This PR adds a new guide generated based on the provided title and description."
        base: main
        labels: "documentation,auto-generated"
