name: Generate Guide and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the Guide'
        required: true
        type: string
      description:
        description: 'Description of the Guide'
        required: true
        type: string

jobs:
  generate_guide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install axios

      - name: Generate Guide Content
        env:
          GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}
        run: |
          node .github/scripts/generateGuide.js "${{ github.event.inputs.title }}" "${{ github.event.inputs.description }}"

      - name: Commit and Push Guide
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "add-guide-${{ github.event.inputs.title }}"
          git add guide.md
          git commit -m "Add guide: ${{ github.event.inputs.title }}"
          git push origin "add-guide-${{ github.event.inputs.title }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Add new guide'
          body: 'This PR adds a new guide to the repository.'
          base: main
          branch: ${{ github.head_ref }}
