name: Generate Guide with Google Gemini API

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the Guide'
        required: true
        default: 'Ingest Cloud Resources using New Relic'
      description:
        description: 'Description of the Guide'
        required: true
        default: 'This guide should be structured in the same way other guides in docs.getport.io/guides are structured.'
      model:
        description: 'The Google Gemini Model to use'
        required: false
        default: 'projects/your-project-id/locations/global/models/gemini-1.5-flash-latest'

jobs:
  generate-guide:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install googleapis

    - name: Generate Guide Content using Gemini API
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        TITLE: ${{ github.event.inputs.title }}
        DESCRIPTION: ${{ github.event.inputs.description }}
        MODEL: ${{ github.event.inputs.model }}
      run: |
        node generateGuide.js

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'Add new guide'
        body: 'This PR adds a new guide to the repository.'
        base: main
        branch: ${{ github.head_ref }}
