name: kubesec

on:
  push:
    branches: [ "main" ]

jobs:
  kubelinter:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: exampleFile.yaml
          config: .kube-linter/config.yaml
          format: sarif
          output-file: kube-linter.sarif

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kube-linter.sarif
