name: Port demo action
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)
        type: string
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: create repo
        uses: octobay/create-repository-action@v1
          with:
            name: ${{ inputs.name }}
            org: ${{ github.repository_owner }}
            access-token: ${{ secrets.ORG_ADMIN_TOKEN }}
            private-repo: true
            initalize-repo: true
