name: Create repo
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "Repo name to deploy"
        type: string
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: echo-deploy
        run: echo ${{ inputs.name }}

  try:
    runs-on: ubuntu-latest
    name: tryRepo
    steps:
      - name: another
        uses: octobay/create-repository-action@v1
        with:
          name: '${{ inputs.name }}'
          org: 'hadar-co'
          access-token: 'portAction'
          private-repo: true
          initalize-repo: true
  
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: another
        uses: octobay/create-repository-action@v1
        with:
          name: '${{ inputs.name }}'
          org: 'hadar-co'
          access-token: 'portAction'
          private-repo: true
          initalize-repo: true
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Creating GitHub Organization Repository
        uses: repo-ctrl/create-repo-action@main 
        id: create-repo
        with:
          repo-name: '${{ inputs.name }}'
          org-admin-token: '${{ secrets.ORG_ADMIN_TOKEN }}'
      - name: Log URL to the repo
        run: echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"
