name: Port demo action
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "Repo name to deploy"
        type: string
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Create Repository
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }} # Replace with your secret's name
        run: |
          # Create a repository using the GitHub REST API
          org_name="hadar-co"
          repo_name="new-repo-name"
          curl -X POST -H "Authorization: token $GH_TOKEN" "https://api.github.com/orgs/$org_name/repos" -d "{\"name\":\"$repo_name\",\"private\":false}"
