name: Port demo action
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "Repo name to deploy"
        type: string
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Create Private Repository
        env:
          GH_PAT: ${{ secrets.ORG_ADMIN_TOKEN }}
        run: |
          # Get the current organization and repository name
          ORG=$(basename $GITHUB_REPOSITORY)
          REPO_NAME='${{ inputs.name }}'

          # Create the repository using the GitHub API
          curl -X POST \
            -H "Authorization: token $GH_PAT" \
            -d '{
              "name": "'"$REPO_NAME"'",
              "private": true
            }' \
            "https://api.github.com/orgs/$ORG/repos"
