name: kubesec

on:
  push:
    branches: [ "main" ]

jobs:
  kubesec:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@master
        with:
          input: exampleFile.yaml
