on:
  workflow_dispatch:


jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create an issue
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        repo: ${{ github.context.repo.repo}}
        title: Simple test issue
        body: my new issue
