on:
  workflow_dispatch:
    inputs:
      # Note that the inputs are the same as the payload (workflowInputs) defined in the automation
      rule_result_name:
        description: 'The rule result name'
        required: true
        type: string
      entity_link:
        description: 'A link to the evaluated entity'
        required: true
        type: string

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.rule_result_name }} and also ${{ inputs.entity_link }}
