on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  imgbuild:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@master
      #  with:
      #    repository: datreeio/drone-datree
      #- run: "ls -al"
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: datree
        uses: hadar-co/action-datree@main
        with:
          path: "blah.yaml"
          cliArguments: "-s 1.23.1"

