on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  imgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: datree
        uses: datreeio/action-datree@main
        with:
          path: 'test.yaml'
          cliArguments: '--only-k8s-files -o simple'
      
          
