on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  imgbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: datreeio/drone-datree
      - run: "ls -al"
      
      #- name: Checkout
      #  uses: actions/checkout@v2
      
      #- name: datree
      #  uses: datreeio/action-datree@main
      #  with:
      #    #path: 'test.yaml testchart/templates/deployment.yaml'
      #    path: "**/*.yaml"
      #    cliArguments: "-s 1.23.1"

