on: [push]

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  datree_test_job:
    runs-on: ubuntu-latest
    name: Datree policy check
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Datree policy check
        uses: hadar-co/dtgatest@main
        with:
          file: 'test.yaml'
          options: '--output simple'
          token: ''
