on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  imgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: datree
        uses: hadar-co/action-datree@main
        with:
          #path: 'test.yaml testchart/templates/deployment.yaml'
          path: '**/*.yaml'
          cliArguments: '-o simple'
      
          
