on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  imgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo '### Hello before! :rocket:' >> $GITHUB_STEP_SUMMARY
      
      - name: datree
        uses: hadar-co/action-datree@main
        with:
          path: 'test.yaml'
          cliArguments: '--schema-version 1.20.0'
      
      - name: showthis
        run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
          
